index.html, style.css
**Feature-1**
Before
After
- Summary- Improved the typewriter effect by changing the relative margin and padding and shifted the typewriter to the next line, looks more clean
**Feature-2**
Before
After
- Summary- Added and removed Bootstrap 5 classes to make it look good and improved the margin and padding of the navigation bar so it doesn't look clumsy.
Shaurya | Gssoc Contributor 
@PranavBarthwal Make sure to pull with the required tags.
Happy to collaborate on more features.
=> Improved NavigationMenu and Typewriter Effect

index.html, style.css
Date input format changed
fixes: #19
Before:
https://github.com/PranavBarthwal/cosmoXplore/assets/169196836/1de4c3fb-eff8-4665-b30e-78c624286241
After fixes:
https://github.com/PranavBarthwal/cosmoXplore/assets/169196836/e840ec6e-9859-498d-99d0-ccebe4c858ef
=> date input changed

style.css
Issue No. : #36 
https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/06cb321a-ce5c-4074-af9a-f29907d9caa1
=> Floating Animation On Images 

index.html, style.css
Issue No. : #54 
https://github.com/PranavBarthwal/cosmoXplore/assets/123383817/84155a47-0226-4e32-a254-34a7664b2f75
- [X ] I have mentioned the issue number in my Pull Request.
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have gone through the  `contributing.md` file before contributing
=> Autotype element overlapping

index.html, style.css
Reverts PranavBarthwal/cosmoXplore#89
=> Revert "Added Styling to Home Page"

index.html
Fixes #99 
https://github.com/PranavBarthwal/cosmoXplore/assets/123383817/9fadb990-1d3d-42b9-a2c2-4985fa4d7962
=> Incorrect string autotyping

index.html
Fixes #45 
**As stated earlier, I have slowed down the speed and made it smoother**
https://github.com/PranavBarthwal/cosmoXplore/assets/115486960/793d0185-c0f3-4eb6-a9ca-249393d4a7fa
https://github.com/PranavBarthwal/cosmoXplore/assets/115486960/5e048cfb-33e6-4738-a769-bc4593d5ac57
https://github.com/PranavBarthwal/cosmoXplore/assets/115486960/d3c9983e-3133-43bb-9e40-94df55348144
- [ x] I have mentioned the issue number in my Pull Request.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have gone through the  `contributing.md` file before contributing
=> Added animation with slow speed

index.html
Fixes #90 
https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/1d0b37f3-f072-4588-9e9c-63270f3db056
=> Typing Effect is Breaking the Word Wrap

CONTRIBUTING.md
=> Missing CONTRIBUTING.md File in Repository

app.js, index.html, style.css
Issue number - #106
Fixes :
1. Implemented slideshow functionality to the Mars Rover photo viewer, allowing users to navigate through multiple images captured by the rover's cameras. 
2. Added "Next" and "Previous" buttons to the photo viewer interface, enabling users to move forward and backward in the slideshow.
3. Updated the user interface to display the current image and camera information as users navigate through the slideshow.
https://github.com/PranavBarthwal/cosmoXplore/assets/78632385/83041d1d-f1d7-42a2-b92e-e07891c19892
Overall these changes enhance the Mars Rover photo viewer by adding interactive slideshow functionality, improving user engagement, and providing a smoother navigation experience.
=> [NEW FEATURE] : Multi-Camera Mars Rover Image Viewer

index.html, style.css
Issue #91 
##Before Changes:
https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/9d3c7d4f-72c0-4a1f-9f08-9912a7e13b94
https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/af7a88b7-d8b0-460f-b28a-0f6dc6b9d925
**Code Changes**
`<div class="l">`
`<div class="spinner">`
`</div>`
`</div>`
`<script>`
` window.addEventListener("load", () => {`
`  const loader = document.querySelector(".l");`
` loader.classList.add("l--hidden");` 
`  loader.addEventListener("transitionend", () => {`
` document.body.removeChild(loader);`
` });`
` });`
` window.addEventListener("load", () => {`
`const loader = document.querySelector(".spinner");`
`loader.classList.add("spinner--hidden");`
` loader.addEventListener("transitionend", () => {`
`document.body.removeChild(loader);`
`});`
` });` …
=> Would like to add preloader?

index.html, style.css
Fixes #53
https://github.com/PranavBarthwal/cosmoXplore/assets/134795697/362f4ace-5c08-4620-85db-77d98d26d5e8
=> Redesigning the complete navbar

index.html
=> [Doc]: calendar date not visible!

index.html
Added icons in the Navbar links  and contact us page
#165
=> Added icons in the Navbar links  and contact us page

index.html
Reverts PranavBarthwal/cosmoXplore#171
=> Revert "Added icons in the Navbar links  and contact us page"

index.html
issue #196
Fixes #196
After Chnages:
https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/862fa388-8315-4394-b776-b792e05c2705
Code Changes:
```
<li class="nav-item " id="new">
<a class="nav-link text-light decorate-text" href="./Pages/asteroid-info/index.html">NeoWs</a>
</li>
<li class="nav-item " id="epic">
<a class="nav-link text-light decorate-text" href="./Pages/earthPics/index.html">EPIC View</a>
</li>
```
=> Add buttons for all pages in navbar

README.md, contributing.md
=> Adding contributing and readme

package.json, src/App.jsx, src/components/ErrorBoundary.jsx
=> error boundary added

.github/ISSUE_TEMPLATE/doc_report.yml, .gitignore, src/App.css, src/components/DisplayDetails.jsx
fixes : #226 
I have rectified the typos by reviewing all the files and also updated the git ignore file.
=> Typos in source code

index.html, package.json
Favicon icon missing #240 
Issue No. : 240
=> favicon icon missing

src/components/Navbar/Navbar.jsx, src/components/Navbar/navabar.css
: Issue No. : #242 
- [ ✅] I have mentioned the issue number in my Pull Request.
- [✅ ] I have commented my code, particularly in hard-to-understand areas
- [✅ ] I have gone through the  `contributing.md` file before contributing
=> made navbar static

src/App.css, src/components/DisplayDetails/DisplayDetails.jsx, src/components/Navbar/Navbar.jsx, src/main.jsx, src/pages/Home/Home.jsx, src/pages/MarsRover/MarsRover.jsx
closes: #225 
https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/77005df1-add3-48d9-819c-2a6c90551919
=> martian rover imagery page

.env.demo, README.md, src/components/BackGround/BackGround.jsx, src/components/BackGround/BackGround.module.css, src/components/Background/BackGround.module.css
closes: #300 
I've added instructions to add a `.env` file and added `DEMO_KEY` for development purposes.
=> [Doc]: Update Readme to add Environment Variables.

contributing.md
=> [Doc]: Update contributing.md for github Desktop

README.md
issue #317
Issue No. :  #317 
Added code
```
---
<h2><img src="https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Travel%20and%20places/High%20Voltage.png" alt="High Voltage" width="40" height="40" /><font size="6">Tech Stack</font></h2>
<a href="https://developer.mozilla.org/en-US/docs/Glossary/HTML5"><img src="https://img.shields.io/badge/HTML5-E34F26.svg?style=for-the-badge&logo=HTML5&logoColor=white"></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"><img src="https://img.shields.io/badge/JavaScript-F7DF1E.svg?style=for-the-badge&logo=JavaScript&logoColor=black"></a>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS"><img src="https://img.shields.io/badge/CSS3-1572B6.svg?style=for-the-badge&logo=CSS3&logoColor=black"></ …
```
=> [Doc]: Improving main Readme/md file

src/main.jsx, src/pages/404 Page/Notfound.css
=> [fix] : Website Main page background colour

.github/workflows/mkdocs.yaml, mkdocs/docs/aboutus.md, mkdocs/docs/gettingstarted.md, mkdocs/docs/index.md, mkdocs/mkdocs.yml, mkdocs/requirements.txt, package.json
#closes: #366 
i have setup the mkdocs folder and had content written in the markdown files name : index.md , about us.md and getting started.md .. more modification to the content can be done like adding screenshots and logo s for the site.
please tell that if everythings fine or do i need to make changes.
=> Documentation added using mkdocs

src/index.css
closes: #340 
Please review my pull request.
=> Added customised scrollbar to the website

src/pages/MarsRover/MarsRover.jsx, src/pages/MarsRover/MarsRover.module.css
closes: #379 
https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/30d5c286-8ed5-4445-8bc4-ea33581dbc84
@surajvast1 @PranavBarthwal  please review this PR.
=> [Feat]: Enhancing Martian Imagery Page

src/components/Chatbot/chatbot.css
=> Chatbot icon alignment

src/components/ScrollToTop/ScrollToTop.module.css
Reverts PranavBarthwal/cosmoXplore#384
=> Revert "Resolved Overlapping of Chatbot and Scroll to Top Button"

package.json, src/components/Hero/Hero.jsx, src/components/Navbar/Navbar.jsx
Issue number:- #359  
https://github.com/PranavBarthwal/cosmoXplore/assets/93486108/594ff858-c31d-45d1-92dd-251a256fe723
- [ X] I have mentioned the issue number in my Pull Request.
- [X ] I have gone through the  `contributing.md` file before contributing
I have just added a smooth scroll effect on the homepage and did nothing to the navbar hover because it was already completed by someone else.
=> Adding a smooth scroll effect to the website and hover effects to the navbar.

src/components/Apod/Apod.module.css
closes: #374 
Please check it and let me know if any changes, Thank you!
=> Fix: Made image in APOTD responsive.

.github/workflows/autocomment-iss-close.yml
closes: #402 
After issue is closed we can see the comment.
Description
This PR introduces an automated commenting system triggered whenever an issue is closed within our project management platform. The system generates a predefined comment to acknowledge issue resolution, including reasons for closure, related pull requests or commits, and expressions of gratitude to contributors.
=> Automatic Comment on Issue Closure

src/index.css
Hey @PranavBarthwal and @surajvast1   | issue closes #431
I have Re-styled the "Vertical Scrollbar" Matching to "Website Design" Theme:
- Change styles
- Added Hover effect
- Gradient color
https://github.com/PranavBarthwal/cosmoXplore/assets/101971980/d454c648-2665-439c-b7da-40b0fee8f297
=> Re-styled the "Vertical Scrollbar" Matching to "Website Design" Theme 

src/components/Footer/Footer.jsx
=> Twitter to X

.github/workflows/auto-label-issues.yml, .github/workflows/auto-label-pr.yml
=> Automatic addition od GSSOC , Bug , Enchancement and Documnetation label

package.json, src/components/Navbar/Navbar.jsx, src/main.jsx, src/pages/Login/page.jsx
@PranavBarthwal I have added Login/Signup Page to the website. Kindly review this.
Fixes issue #411 
closes: #411 
@PranavBarthwal  Kindly review this.
=> Login/Signup Page 

src/components/Navbar/Navbar.jsx
closes:  #467 
https://github.com/user-attachments/assets/259054ce-8a73-4262-bdc5-e5cb2e34032b
=> Close dropdown auto on choosing any option #467
